spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weconnect_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Dùng Flyway để quản lý schema, không dùng update của Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379